### ISSUE TITLE
关于论文中TPLite应用到二进制sca部分疑问

### ISSUE THREAD

**Issue by xiaoyao377905** [Tricker-z/TPLite#1]
_“同时，我们将TPLite的源码复用关系应用于下游的二进制SCA任务中，进一步提高了二进制SCA对第三方库的识别能力。“_
关于这部分论文中没有详细说明，可以具体讲讲如何做的吗? 
通过TPL库来补全二进制sca检测中的漏报问题吗？ （猜测）

**Comment by Tricker-z** [comment]
Hi

Please discuss the content of the paper by email. Only the technology is discussed here.

Feel free to contact me if you have any further concerns.
