### ISSUE TITLE
Dependencies of TPLs

### ISSUE THREAD

**Issue by whj0401** [Tricker-z/TPLite#2]
Thank you for your impressive work.
I noticed that you also provide the sources of your TPLs [here](https://github.com/Tricker-z/TPLite/blob/main/data/input/tpls_1k_url.csv). May I ask if their ground truth dependencies are available?
Thank you in advance for your support and suggestions.

**Comment by bitcalc** [comment]
Hi whj0401,

Any progress on your issue?

Since you closed this issue, I guess that you might have found the dependency data somewhere. If so, could you please share it? I'm looking for it too.

Thanks.
