### ISSUE TITLE
Issue Regarding the Dataset

### ISSUE THREAD

**Issue by zengjia1** [Tricker-z/TPLite#3]
Hello, I apologize for taking up your time. I have a few questions about TPLite that I would like to ask you:

1. Have you constructed a database containing 10,060 TPL signatures?
2. How much memory did you use? I converted over 400 TPLs from the tpls_1k_url.csv file into signatures, and it already took up 300GB. If I want to convert all TPLs into signatures, it seems to be too large.

**Comment by Tricker-z** [comment]
Hi

It's true that SCA requires a lot of resources. In fact, we deployed the whole process on a big data system, and what's on Github is just an algorithm demo.  I'm sorry I'm not sure how much memory it would consume to run it directly.

Best regards
